"""adding admin flag to user

Revision ID: 778d87b9a18b
Revises: 6cf202a83095
Create Date: 2024-09-02 20:12:34.885894

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '778d87b9a18b'
down_revision = '6cf202a83095'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('is_admin', sa.Boolean(), nullable=False))
    op.alter_column('User', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('User', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('User', 'is_admin')
    # ### end Alembic commands ###
